---
- hosts: all
  become: true
  tasks:
    - name: Upgrade kernel to version 5.81
      package:
        name: linux-image-5.81
        state: latest
    - name: Create users from text file
      user:
        name: "{{ item }}"
        password: "{{ 'temporary' | password_hash('sha512') }}"
        update_password: always
      with_items: "{{ lookup('file', 'users.txt') }}"
    - name: Install Apache web server
      apt:
        name: apache2
        state: present
    - name: Start Apache service
      service:
        name: apache2
        state: started
    - name: Enable Apache service to start on boot
      systemd:
        name: apache2
        state: enabled
    - name: Create virtual host configuration file
      template:
        src: templates/virtualhost.conf.j2
        dest: /etc/apache2/sites-available/example.com.conf
    - name: Enable virtual host
      apache2_module:
        name: ssl
        state: enabled
    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
    - name: Create flag captured text file
      file:
        path: /var/www/html/flag.txt
        mode: 0700
        owner: root
        group: root
        content: "Flag captured"
    - name: Install vulnerable kernel
      package:
        name: linux-image-4.8.0-58-generic
        state: latest
  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
