---
- hosts: localhost
  become: yes
  remote_user: root1
  become_user: root
#  vars_files:
#    - vars.yml
#  vars:
#    ansible_ssh_private_key_file: "{{key}}"
  tasks:

  - name: Install dependencies
    yum:
      name:
        - wget
        - make
        - gcc
        - kernel-headers
        - kernel-devel
        - libtermcap-devel
      state: present
  - name: create group
    group:
      name: usersgroup
      state: present

  - name: Apache latest version installation
    dnf:
      name: httpd
      state: latest
  - name: Enable service to start on boot up
    service:
      name: httpd
      state: started
  - name: Create firewall rule for apache service
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
  handlers:
  - name: Restart apache service
    service:
      name: httpd
      state: restarted

  - name: Create users
    user: name="{{item}}" shell=/bin/bash home="/srv/{{item}}" groups=usersgroup generate_ssh_key=yes ssh_key_bits=2048
    loop:  "{{ lookup('file', 'users.txt', wantList=True) }}"
  - name: Set password to users
    shell: echo "{{item}}:root" | sudo chpasswd
    no_log: True
    loop:  "{{ lookup('file', 'users.txt', wantList=True) }}"
  - name: Check if file exists
    stat:
      path: linux-4.8.tar.xz
    register: file_stat

  - name: Download kernel source code
    command:  wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.8.tar.xz
    when: file_stat.stat.exists == False
    become: true

  - name: Create restricted file
    lineinfile:
      path: /var/www/restricted.txt
      line: "flag captured"
      create: true

  - name: Set ownership and permissions of restricted file
    file:
      path: /var/www/restricted.txt
      owner: root
      group: root
      mode: 0640
